// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Path to a configuration file. If left empty, it will recursively search in the parent directories for a bolt.yml file": 5,
	"Print version and exit": 2,
	"Run a job":              4,
	"Script management that rides the lighting.": 1,
	"bolt version %s\n":                          3,
	"unknown (built from source)":                0,
}

var enIndex = []uint32{ // 7 elements
	0x00000000, 0x0000001c, 0x00000047, 0x0000005e,
	0x00000076, 0x00000080, 0x000000f6,
} // Size: 52 bytes

const enData string = "" + // Size: 246 bytes
	"\x02unknown (built from source)\x02Script management that rides the ligh" +
	"ting.\x02Print version and exit\x04\x00\x01\x0a\x13\x02bolt version %[1]" +
	"s\x02Run a job\x02Path to a configuration file. If left empty, it will r" +
	"ecursively search in the parent directories for a bolt.yml file"

var frIndex = []uint32{ // 7 elements
	0x00000000, 0x0000002a, 0x00000058, 0x00000077,
	0x0000008f, 0x000000b2, 0x0000014c,
} // Size: 52 bytes

const frData string = "" + // Size: 332 bytes
	"\x02inconnue (compilation depuis les sources)\x02Lancez vos tâches plus " +
	"vite que la lumière.\x02Afficher la version et quitter\x04\x00\x01\x0a" +
	"\x13\x02bolt version %[1]s\x02Exécuter une séquence de tâches\x02Chemin " +
	"vers un fichier de configuration. Si aucune valeur n'est saisie, une rec" +
	"herche dans les dossiers parents pour un fichier bolt.yml sera exécutée."

	// Total table size 682 bytes (0KiB); checksum: 92D78B7D
